import{a as l,S as P,i as n}from"./assets/vendor-CIF6YjI2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="56144354-a08717fc8df2b40204429c095";l.defaults.baseURL="https://pixabay.com/api/";async function d(s,r){return(await l.get("",{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more-btn"),$=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:c,comments:w,downloads:M})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${o}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${t}</p>
        <p class="info-item"><b>Views</b><br>${c}</p>
        <p class="info-item"><b>Comments</b><br>${w}</p>
        <p class="info-item"><b>Downloads</b><br>${M}</p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),$.refresh()}function q(){u.innerHTML=""}function y(){f.classList.remove("is-hidden")}function g(){f.classList.add("is-hidden")}function p(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}const L=document.querySelector(".form"),B=document.тз;let i=1;const v=15;L.addEventListener("submit",E);B.addEventListener("click",O);async function E(s){if(s.preventDefault(),searchQuery=s.currentTarget.elements.searchQuery.value.trim(),searchQuery===""){n.warning({message:"Please enter a search query!"});return}i=1,q(),b(),y();try{const r=await d(searchQuery,i);if(r.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(r.hits);const o=Math.ceil(r.totalHits/v);i<o?p():n.info({message:"We're sorry, but you've reached the end of search results."})}catch(r){n.error({message:`Error: ${r.message}`})}finally{g(),L.reset()}}async function O(){i+=1,b(),y();try{const s=await d(searchQuery,i);h(s.hits);const r=document.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const o=Math.ceil(s.totalHits/v);i>=o?n.info({message:"We're sorry, but you've reached the end of search results."}):p()}catch(s){n.error({message:`Error: ${s.message}`})}finally{g()}}
//# sourceMappingURL=index.js.map
