import{a as d,S as M,i as n}from"./assets/vendor-CIF6YjI2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="56144354-a08717fc8df2b40204429c095";d.defaults.baseURL="https://pixabay.com/api/";async function u(o,t){return(await d.get("",{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:S,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${r}</p>
        <p class="info-item"><b>Views</b><br>${c}</p>
        <p class="info-item"><b>Comments</b><br>${S}</p>
        <p class="info-item"><b>Downloads</b><br>${q}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){f.innerHTML=""}function g(){m.classList.remove("is-hidden")}function p(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const v=document.querySelector(".form"),E=document.querySelector(".load-more-btn");let l="",i=1;const w=15;v.addEventListener("submit",O);E.addEventListener("click",H);async function O(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),l===""){n.warning({message:"Please enter a search query!"});return}i=1,B(),L(),g();try{const t=await u(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits);const s=Math.ceil(t.totalHits/w);i<s?b():n.info({message:"We're sorry, but you've reached the end of search results."})}catch(t){n.error({message:`Error: ${t.message}`})}finally{p(),v.reset()}}async function H(){i+=1,L(),g();try{const o=await u(l,i);y(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(o.totalHits/w);i>=s?n.info({message:"We're sorry, but you've reached the end of search results."}):b()}catch(o){n.error({message:`Error: ${o.message}`})}finally{p()}}
//# sourceMappingURL=index.js.map
